version: '3'
services:
  db:
    image: 'postgres:latest'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432'
    env_file:
      - .env.dev
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      
  django:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todo
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  rq:
    build:
      context: .
      dockerfile: Dockerfile.local
    command: python3 manage.py rqworker default
    volumes:
      - .:/django-rq
    env_file:
      - .env.dev
    depends_on:
      - redis

  rq-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    command: python3 manage.py rqscheduler default
    volumes:
      - .:/django-rq
    env_file:
      - .env.dev
    depends_on:
      - redis
      - rq

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "14000:6379"

volumes:
  postgres_data: